# name: Sends an email with AWS SES

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#     inputs:
#       paths:
#         description: 'List of file paths to attach'
#         required: true
#       recipients:
#         description: 'List of email addresses to send the email to'
#         required: true
#       sender:
#         description: 'Email address of the sender'
#         required: true

# jobs:
#   send_email:
#     runs-on: ubuntu-latest
#     env:
#       AWS_REGION: your-aws-region
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       SENDER_EMAIL: ${{ inputs.sender }}
#       RECIPIENT_EMAILS: ${{ inputs.recipients }}
#       ATTACHMENT_FILE_PATHS: ${{ inputs.paths }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x

#       - name: Install dependencies
#         run: pip install boto3

#       - name: Send email
#         run: |
#           python send_email.py
#           echo "::set-output name=result::Email sent!"
#         env:
#           AWS_REGION: ${{ env.AWS_REGION }}
#           AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
#           SENDER_EMAIL: ${{ env.SENDER_EMAIL }}
#           RECIPIENT_EMAILS: ${{ env.RECIPIENT_EMAILS }}
#           ATTACHMENT_FILE_PATHS: ${{ env.ATTACHMENT_FILE_PATHS }}
#         shell: bash
#         id: send-email

#   print_result:
#     needs: send_email
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print result
#         if: always()
#         run: |
#           echo "${{ needs.send_email.outputs.result }}"