name: tagging strategy

on:
  push:
    branches:
      - master
    
jobs:
  simple-app:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Tima
      - name: Log Greeting Tima
        run: |
          echo "${{steps.greet.outputs.time}}"
          echo "${{steps.greet.outputs.id}}"
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          message: "Latest release"
