# name: tagging strategy

# on:
#   push:
#     branches:
#       - master
#       - stage
# jobs:
#   simple-app:
#     runs-on: ubuntu-latest
#     steps:
#       - name: simple JS Actions
#         id: greet
#         uses: actions/hello-world-javascript-action@v1
#         with: 
#           who-to-greet: Timacha
#       - name: Log Greeting Timacha
#         run: |
#           echo "${{steps.greet.outputs.time}}"
#           echo "${{steps.greet.outputs.id}}"
#   create-tag:
#   # how to make sure that step runs if only there is no error on github actions workflow. 
#     runs-on: ubuntu-latest
#     outputs:
#       branch: ${{ steps.branch.outputs.cur_branch }}
#     steps:
#       # if: branch is uat and Prod
#       - name: checkout
#         uses: actions/checkout@v2
#         with:
#           ref: ${{ needs.create-tag.outputs.branch }}
#       - name: current branch
#         run: echo "::set-output name=cur_branch::${GITHUB_REF##*/}"
#         id: branch
#       - name: set env
#         run: |
#           git fetch --prune --unshallow
#           echo "::set-output name=tag::$(git describe --abbrev=0 --tags || echo 'v0.0.0')" 
#         id: tag
#       - name: echo tag
#         run: echo ${{ steps.tag.outputs.tag }}
#       - name: run scripts
#         working-directory: scripts
#         run: echo "::set-output name=version::$(bash auto_increment_tag_version.sh ${{ steps.tag.outputs.tag }})"
#         id: current_version
#       - name: branch
#         run: |
#           echo ${{ steps.branch.outputs.cur_branch }}
#           echo ${{ github.ref }}
#       - name: Create a tag
#         uses: rickstaa/action-create-tag@v1
#         with:
#           tag: "v.${{ steps.branch.outputs.cur_branch }}.${{ steps.current_version.outputs.version }}"
#           message: "Latest release"

