name: tagging strategy

on:
  push:
    branches:
      - master
      - stage
jobs:
  simple-app:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Tima
      - name: Log Greeting Timacha
        run: |
          echo "${{steps.greet.outputs.time}}"
          echo "${{steps.greet.outputs.id}}"
  create-tag:
  # how to make sure that step runs if only there is no error on github actions workflow. 
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.cur_branch }}
    steps:
      # if: branch is uat and Prod
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.create-tag.outputs.branch }}
      - name: current branch
        run: echo "::set-output name=cur_branch::${GITHUB_REF##*/}"
        id: branch
      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: print latest tag
        run: echo ${{ steps.get-latest-tag.outputs.tag }}
      #   # if no tag found
      # - name: crete new tag manually
      #   if: steps.get-latest-tag.outputs.tag == 'v0.0.0'
      #   run: |
      #     git tag "v.${{ steps.branch.outputs.cur_branch }}.0.0.1"
      #     git push origin "v.${{ steps.branch.outputs.cur_branch }}.0.0.1"
      - name: run scripts
        # if: steps.get-latest-tag.outputs.tag != 'v0.0.0'
        working-directory: scripts
        run: echo "::set-output name=version::$(bash auto_increment_tag_version.sh ${{ steps.get-latest-tag.outputs.tag }})"
        id: current_version
      - name: branch
        run: |
          echo ${{ steps.branch.outputs.cur_branch }}
          echo ${{ github.ref }}
      - name: Create a tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v.${{ steps.branch.outputs.cur_branch }}.${{ steps.current_version.outputs.version }}"
          message: "Latest release"

