name: read JSON

on:
  push:
    branches:
      - master
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.vars.outputs.run_id }}
    env:
      test: test
    steps:
      - name: create json
        run: |
          echo '{
            "job_id": "${{ github.job }}",
            "run_id": "${{ github.run_id }}"
          }' > email_vars.json

          cat email_vars.json

      - name: create vars 
        id: vars
        run: |
          all_vars=$(cat email_vars.json)
          echo "run_id=$(cat $all_vars| jq -r '.run_id')" >> $GITHUB_OUTPUT
  
  read_job:
    runs-on: ubuntu-latest
    needs: config
    steps:
      - name: read_work
        id: read
        run: |
         echo "${{ needs.config.outputs.run_id }}"
          echo "#######testing######"





