name: test string
run-name: this is ${{ github.job }}
on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '*/6 * * * *'
    - cron: '*/7 * * * *'
    - cron: '*/8 * * * *'

jobs:
  first_job:
    if: contains(fromJSON('['*/6 * * * *', '*/8 * * * *']'), github.event.schedule)
    runs-on: ubuntu-latest
    steps:
    
      # - name: check for time 
      #   run: |
      #     if: contains(github.event.schedule, '*/5 * * * *')
      #       echo "is_update_time="True" >> GITHUB_OUTPUT
      #       echo "${outputs.branch}"
          
      - name: run trough srings
        # if: needs.prep.outputs.branch == True
        run: | 
          echo 'IT IS WORKING'
  second_job:
    if: contains(fromJSON('['*/5 * * * *', '*/7 * * * *']'), github.event.schedule)
    runs-on: ubuntu-latest
    steps:
      - name: test github job
        run: |
          echo "this is ${{ github.job }}"
        

